### ISSUE TITLE
Error when reading from django File object

### ISSUE THREAD

**Issue by vkurup** [caktus/cordwainer#1]
My pseudocode looked something like this:

```
from cordwainer import csv
csv_file = self.cleaned_data['csv_file']
reader = csv.reader(csv_file, encoding='utf-8')
for row in reader:
   ...
```

And when it tried to iterate over the reader I'd get an error that looked something like this:

```
TypeError: InMemoryUploadedFile object is not an iterator
```

Which led to me to find out that while the python file type IS an iterator, the django File object is not (or it's an incomplete one). 

Python:

```
>>> f1 = file('manage.py')
>>> next(f1)
'#!/usr/bin/env python\n'
```

Django (supports the `iter()` method, but not the `next()` method):

```
>>> from django.core.files import File
>>> f = File('asd')
>>> next(f)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: File object is not an iterator
>>> iter(f)
<generator object __iter__ at 0x7fecede1c6e0>
```

Here's the [line](https://github.com/caktus/cordwainer/blob/master/cordwainer/utils.py#L50) where `self.stream` is expected to support the `next()` method, but I'm not sure how to fix it. 

A workaround is to take the Django file instance and convert it to an iterator with `codecs.getreader()`

Is this a django bug? [This](https://docs.python.org/2/library/stdtypes.html#iterator-types) says that iterator objects should support the `__iter__()` method and the `next()` method.

**Comment by vkurup** [comment]
For completeness, here's the full stacktrace of the error:

```
ERROR: test_bulk_form_process_bad_header (registration.tests.test_registration.TestBulkUploadProcessForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vkurup/dev/RescueSMS/registration/tests/test_registration.py", line 471, in test_bulk_form_process_bad_header
    status_message, error_message = form.process(self.tenant)
  File "/home/vkurup/dev/RescueSMS/registration/forms.py", line 143, in process
    if len(reader.fieldnames) != len(expected_headers):
  File "/usr/lib/python2.7/csv.py", line 90, in fieldnames
    self._fieldnames = self.reader.next()
  File "/home/vkurup/.virtualenvs/rescuesms/local/lib/python2.7/site-packages/six.py", line 518, in next
    return type(self).__next__(self)
  File "/home/vkurup/.virtualenvs/rescuesms/local/lib/python2.7/site-packages/cordwainer/csv.py", line 71, in __next__
    row = six.next(self.csv_reader)
  File "/home/vkurup/.virtualenvs/rescuesms/local/lib/python2.7/site-packages/six.py", line 518, in next
    return type(self).__next__(self)
  File "/home/vkurup/.virtualenvs/rescuesms/local/lib/python2.7/site-packages/cordwainer/utils.py", line 50, in __next__
    return change_encoding(six.next(self.stream), self.from_, self.to)
TypeError: SimpleUploadedFile object is not an iterator
```

**Comment by dpoirier** [comment]
I think what you've got there is not a Django `File` object, but a Django `UploadedFile` object (https://docs.djangoproject.com/en/1.7/ref/files/uploads/), which is not iterable but has some other methods that can be used to read from it.   It looks like `.chunks()` will return a generator that should be okay to pass to csv.reader.

(Why UploadedFile is not directly iterable is a mystery to me.  Maybe we should submit a patch...)

**Comment by vkurup** [comment]
I tried it with a Django `File` object above as well. See my Python interpreter examples above. I'll try passing `.chunks()` to `csv.reader()` and report back when I get a chance.
